### ISSUE TITLE
Crash with QMD 1.0.4

### ISSUE THREAD

**Issue by lerokko** [CleanroomMC/Multiblocked#10]
When using multiblocked with QMD I get the following/crash error:

```
net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Multiblock'd (multiblocked)
Caused by: java.lang.NoSuchMethodError: nc.multiblock.tile.TileMultiblockPart.<init>(Ljava/lang/Class;)V
    at lach_01298.qmd.multiblock.TileCuboidalOrToroidalMultiblockPart.<init>(TileCuboidalOrToroidalMultiblockPart.java:42)
    at lach_01298.qmd.accelerator.tile.TileAcceleratorPart.<init>(TileAcceleratorPart.java:14)
    at lach_01298.qmd.accelerator.tile.TileAcceleratorBeamPort.<init>(TileAcceleratorBeamPort.java:49)
    at lach_01298.qmd.accelerator.block.BlockAcceleratorBeamPort.createNewTileEntity(BlockAcceleratorBeamPort.java:51)
    at net.minecraft.block.Block.createTileEntity(Block.java:1274)
    at com.cleanroommc.multiblocked.api.pattern.util.BlockInfo.fromBlockState(BlockInfo.java:42)
    at com.cleanroommc.multiblocked.common.capability.ParticleQMDCapability.getCandidates(ParticleQMDCapability.java:63)
    at com.cleanroommc.multiblocked.CommonProxy.postInit(CommonProxy.java:65)
    at com.cleanroommc.multiblocked.Multiblocked.postInit(Multiblocked.java:127)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
    at sun.reflect.GeneratedMethodAccessor9.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
    at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
    at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
    at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
    at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
    at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
    at com.google.common.eventbus.EventBus.post(EventBus.java:217)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
    at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
    at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
    at net.minecraft.client.Minecraft.init(Minecraft.java:535)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3931)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
```

**Comment by Rongmario** [comment]
Downgrade NuclearCraft: Overhauled from `2o.6.0-1.12.2` to `2o.5.5-1.12.2` as discussed on discord.
