### ISSUE TITLE
Incompatibility with QMD

### ISSUE THREAD

**Issue by Darth-Pikachu** [CleanroomMC/Multiblocked#44]
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  MixinBooter (!mixinbooter-4.2.jar)
  MultiblockedLoadingPlugin (multiblocked-0.5.6.jar)
Contact their authors BEFORE contacting forge

// I bet Cylons wouldn't have this problem.

Time: 5/31/22 7:02 AM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Multiblock'd (multiblocked)
Caused by: java.lang.NoSuchMethodError: nc.multiblock.tile.TileMultiblockPart.<init>(Ljava/lang/Class;)V
	at lach_01298.qmd.multiblock.TileCuboidalOrToroidalMultiblockPart.<init>(TileCuboidalOrToroidalMultiblockPart.java:42)
	at lach_01298.qmd.accelerator.tile.TileAcceleratorPart.<init>(TileAcceleratorPart.java:14)
	at lach_01298.qmd.accelerator.tile.TileAcceleratorBeamPort.<init>(TileAcceleratorBeamPort.java:49)
	at lach_01298.qmd.accelerator.block.BlockAcceleratorBeamPort.func_149915_a(BlockAcceleratorBeamPort.java:51)
	at net.minecraft.block.Block.createTileEntity(Block.java:1274)
	at com.cleanroommc.multiblocked.api.pattern.util.BlockInfo.fromBlockState(BlockInfo.java:42)
	at com.cleanroommc.multiblocked.common.capability.ParticleQMDCapability.getCandidates(ParticleQMDCapability.java:63)
	at com.cleanroommc.multiblocked.CommonProxy.postInit(CommonProxy.java:71)
	at com.cleanroommc.multiblocked.Multiblocked.postInit(Multiblocked.java:118)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:637)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:754)
	at net.minecraftforge.fml.client.FMLClientHandler.finishMinecraftLoading(FMLClientHandler.java:336)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:535)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:378)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1094459816 bytes (1043 MB) / 1948778496 bytes (1858 MB) up to 7546077184 bytes (7196 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx8096m -Xms256m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 8 mods loaded, 8 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID           | Version      | Source                         | Signature                                |
	|:----- |:------------ |:------------ |:------------------------------ |:---------------------------------------- |
	| LCHIJ | minecraft    | 1.12.2       | minecraft.jar                  | None                                     |
	| LCHIJ | mcp          | 9.42         | minecraft.jar                  | None                                     |
	| LCHIJ | FML          | 8.0.99.99    | forge-1.12.2-14.23.5.2860.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | forge        | 14.23.5.2860 | forge-1.12.2-14.23.5.2860.jar  | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJ | mixinbooter  | 4.2          | minecraft.jar                  | None                                     |
	| LCHIE | multiblocked | 0.5.6        | multiblocked-0.5.6.jar         | None                                     |
	| LCHI  | nuclearcraft | 2o.6.1       | NuclearCraft-2o.6.1-1.12.2.jar | None                                     |
	| LCHI  | qmd          | 1.0.4        | QMD-1.0.4-1.12.2.jar           | None                                     |

	Loaded coremods (and transformers): 
MixinBooter (!mixinbooter-4.2.jar)
  
MultiblockedLoadingPlugin (multiblocked-0.5.6.jar)
  com.cleanroommc.multiblocked.core.ASMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 511.65' Renderer: 'NVIDIA GeForce GTX 1060 3GB/PCIe/SSE2'
```

**Comment by Yefancy** [comment]
not a mbd's issue. report to qmd
