### ISSUE TITLE
Mod crashes on servers

### ISSUE THREAD

**Issue by AzureDoom** [CleanroomMC/Multiblocked#58]
Mod version: multiblocked-0.7.3.jar

```
[29.09 05:23:42] [Server] thread/ERROR [FML]Exception caught during firing event net.minecraftforge.event.RegistryEvent$Register@29314367:
[29.09 05:23:42] [Server] java.lang.NoClassDefFoundErrorcom/mojang/realmsclient/util/JsonUtils
[29.09 05:23:42] [Server] at com.cleanroommc.multiblocked.api.definition.ComponentDefinition.fromJson(ComponentDefinition.java:151) ~[ComponentDefinition.class:?]
[29.09 05:23:42] [Server] at com.cleanroommc.multiblocked.api.definition.PartDefinition.fromJson(PartDefinition.java:42) ~[PartDefinition.class:?]
[29.09 05:23:42] [Server] at com.cleanroommc.multiblocked.api.registry.MbdComponents.registerComponentFromResource(MbdComponents.java:154) ~[MbdComponents.class:?]
[29.09 05:23:42] [Server] at com.cleanroommc.multiblocked.CommonProxy.registerComponents(CommonProxy.java:98) ~[CommonProxy.class:?]
[29.09 05:23:42] [Server] at com.cleanroommc.multiblocked.CommonProxy.registerBlocks(CommonProxy.java:133) ~[CommonProxy.class:?]
[29.09 05:23:42] [Server] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_345_CommonProxy_registerBlocks_Register.invoke(.dynamic) ~[?:?]
[29.09 05:23:42] [Server] at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
[29.09 05:23:42] [Server] at net.minecraftforge.fml.common.eventhandler.EventBus$1.invoke(EventBus.java:144) ~[EventBus$1.class:?]
[29.09 05:23:42] [Server] at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
[29.09 05:23:42] [Server] at net.minecraftforge.registries.GameData.fireRegistryEvents(GameData.java:845) [GameData.class:?]
[29.09 05:23:42] [Server] at net.minecraftforge.fml.common.Loader.preinitializeMods(Loader.java:630) [Loader.class:?]
[29.09 05:23:42] [Server] at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:99) [FMLServerHandler.class:?]
[29.09 05:23:42] [Server] at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333) [FMLCommonHandler.class:?]
[29.09 05:23:42] [Server] at net.minecraft.server.dedicated.DedicatedServer.init(DedicatedServer.java:125) [nz.class:?]
[29.09 05:23:42] [Server] at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
[29.09 05:23:42] [Server] at java.lang.Thread.run(Thread.java:748) [?:1.8.0_271]
[29.09 05:23:42] [Server] Caused byjava.lang.ClassNotFoundException: com.mojang.realmsclient.util.JsonUtils
[29.09 05:23:42] [Server] at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
[29.09 05:23:42] [Server] at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_271]
[29.09 05:23:42] [Server] at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271]
[29.09 05:23:42] [Server] ... more
[29.09 05:23:42] [Server] Caused byjava.lang.NullPointerException
[29.09 05:23:42] [Server] at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
[29.09 05:23:42] [Server] at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_271]
[29.09 05:23:42] [Server] at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_271]
[29.09 05:23:42] [Server] ... more
```

**Comment by friendlyhj** [comment]
Fixed in `v0.7.4`
